apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
  labels: 
    {{- include "chart.labels" . | indent 4 }}
data:
  key: {{ .Release.Name }}
  chart: {{ quote .Chart.AppVersion }}
  date: {{ now | date "2006-01-02" | quote }}
  {{- if eq .Values.env "production" }}
  paymentToken: "1234"
  {{- else}}
  paymentToken: false
  {{- end }}
  {{- with .Values.value.requriments.limits }}
  memory: {{ .memory }}
  cpu: {{ .cpu }}
  version: {{ $.Values.app.version }}
  {{- end }}
  {{- $map := .Release.Name | upper | quote }}
  map: {{ $map }}
  users:
    {{- range $index, $user := .Values.users }}
    - {{ $user.name }}: "{{ $user.role }} - {{ $index }}"
    {{- end}}
  usersTuple: |-
    {{- range tuple "Anton" "Vasia" }}
    - {{ . }}
    {{- end }}
