apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name }}-clasterip
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.postgres.port }}
    protocol: TCP
  selector:
    components: {{ .Values.postgres.components }}  
